const getCenterPrograms = (centerName) => [
  {
    _archived: false,
    _draft: true,
    deal: false,
    "choose-program-switch": true,
    popular: false,
    "sort-order": 3,
    name: `${centerName} Venue Rental`,
    "body-description": "",
    "external-display-name": "Venue/Field Rental",
    "rich-text":
      '<p id="">Whatever your next event, TOCA has you covered! Whether it\'s a team party, holiday celebration, or any kind of corporate event, TOCA has versatile event spaces and soccer studios that will make your time with us a blast!</p><p id="">Our fields are also available for rent to teams looking for a space to train!</p><h4 id="">Contact Us</h4><p id="">Fill out the form on this page, and our center will contact you to discuss Venue and Field Rental.</p><p id="">‍</p>',
    slug: `${centerName}-4venuerental`,
    "hero-slider-image-first": {
      fileId: "64492d7ee2522e4ff32b5684",
      url: "https://uploads-ssl.webflow.com/60c7be61132e3ad0b40a333d/6345ecaff0489550046961d0_632c8e58b9a9014fc285d3d5_venue.jpeg",
      alt: null,
    },
    centers: ["64492d7ee2522edf462b5519"],
    states: ["64492d7ee2522e0a132b5516"],
    "phone-number-2": "000-000-0000",
    mytoca: false,
  },
  {
    _archived: false,
    _draft: true,
    deal: false,
    "choose-program-switch": true,
    popular: false,
    "sort-order": 5,
    name: `${centerName} Birthday Parties`,
    "body-description": "",
    "external-display-name": "Birthday Parties",
    "rich-text":
      '<p id="">Celebrate your soccer lover with the ultimate beautiful game birthday party! TOCA birthday packages include playtime in our soccer studios, exclusive use of our party area, and a dedicated party coach.</p><h4 id="">Highlights</h4><ul id=""><li id="">Celebrate the soccer lover in your life&nbsp;</li><li id="">Enjoy exclusive use of soccer studios and party area</li><li id="">Make lasting birthday memories with family and friends</li></ul><h4 id="">Contact Us</h4><p id="">Please fill out the form on this page, and our center will contact you to discuss Birthday Parties.</p>',
    slug: `${centerName}-3birthdayparties`,
    "hero-slider-image-first": {
      fileId: "63650f114443c433107341ba",
      url: "https://uploads-ssl.webflow.com/60c7be61132e3ad0b40a333d/6345ecaf99904fbb77bb14bc_632c9598f8eaf9b3b0d155a7_birthdays.jpeg",
      alt: null,
    },
    states: ["64492d7ee2522e0a132b5516"],
    centers: ["64492d7ee2522edf462b5519"],
    "phone-number-2": "000-000-0000",
    mytoca: false,
  },
  {
    _archived: false,
    _draft: true,
    deal: false,
    "choose-program-switch": true,
    popular: false,
    name: `${centerName} About TOCA Football`,
    "body-description": "",
    "external-display-name": "About TOCA Football",
    "rich-text": `<h4 id="">Next Generation Soccer Training</h4><figure id="" class="w-richtext-figure-type-image w-richtext-align-fullwidth" style="max-width:1680px" data-rt-type="image" data-rt-align="fullwidth" data-rt-max-width="1680px"><div id=""><img src="https://uploads-ssl.webflow.com/60c7be61132e3ad0b40a333d/632651d23bb4e85d5f5309a8_210608_ha_toca_training_012_LowRes.jpg" alt="Young boy dribbling a soccer ball" id="" width="auto" height="auto" loading="auto"></div></figure><p id="">TOCA offers technology-enhanced soccer training designed to produce rapid skill improvement and develop well-rounded players. The key is TOCA’s proprietary technology, including the Touch Trainer, Smart Targets, Studio Screens, and personalized data tracking, that take your game to the next level.</p><p id="">Overall, you get at least 250 match-quality touches on the ball per TOCA training session - equivalent to a week full of practices! Additionally, you can see your progress during each training session through real-time stats that give you data-driven feedback on your accuracy, efficiency, quickness, and more.</p><p id="">TOCA’s exclusive training tools will fine-tune your touch, improve your skills and sharpen your in-game awareness and decision-making. Become the player you want to be with TOCA</p><h4 id="">Make Every Touch Count</h4><figure id="" class="w-richtext-figure-type-image w-richtext-align-fullwidth" style="max-width:1680px" data-rt-type="image" data-rt-align="fullwidth" data-rt-max-width="1680px"><div id=""><img src="https://uploads-ssl.webflow.com/60c7be61132e3ad0b40a333d/632bd081d5469fcf0a1625ac_210608_ha_toca_training_026_LowRes.jpg" alt="A soccer ball machine called TOCA Touch Trainer" id="" width="auto" height="auto" loading="auto"></div></figure><p id="">Your first touch on a ball is one of the most important skills to develop. Possessing a good first touch can be the difference between creating a scoring opportunity for your team or gifting one to your opponent.</p><p id="">TOCA’s Touch Trainer is a revolutionary tool that develops your first touch by delivering passes at various speeds and trajectories. Compared to other training programs that produce fewer touches for players, the Touch Trainer is guaranteed to serve a minimum of 200 match-quality touches every training session.</p><p id="">Key to providing you with so many quality touches is TOCA’s innovative “small ball” methodology. Lighter and smaller than a size 5 ball, the TOCA ball reduces physical stress on your body. Our “small ball” also improves your accuracy by honing your ability to target the optimal strike zones on a regulation ball.</p><h4 id="">Train Smart</h4><figure id="" class="w-richtext-figure-type-image w-richtext-align-fullwidth" style="max-width:1680px" data-rt-type="image" data-rt-align="fullwidth" data-rt-max-width="1680px"><div id=""><img src="https://uploads-ssl.webflow.com/60c7be61132e3ad0b40a333d/61943405426fec4317579192_210608_ha_toca_training_025_LowRes.jpg" alt="Young girl training with TOCA Smart Targets" id="" width="auto" height="auto" loading="auto"></div></figure><p id="">Smart Targets light up, acting as a teammate, allowing for game-like scenarios that improve your situational awareness and condition you to make quick, smart decisions.</p><h4 id="">Track Progress in Real-Time</h4><figure id="" class="w-richtext-figure-type-image w-richtext-align-fullwidth" style="max-width:1680px" data-rt-type="image" data-rt-align="fullwidth" data-rt-max-width="1680px"><div id=""><img src="https://uploads-ssl.webflow.com/60c7be61132e3ad0b40a333d/632bd6f131fb05369e058768_210608_ha_toca_training_003_LowRes.jpg" alt="Soccer trainer and player looking at a TV screen with training stats" id="" width="auto" height="auto" loading="auto"></div></figure><p id="">Your real-time performance data is displayed on a studio screen - tracking improvements and inspiring you to find your best. </p><h4 id="">Join the TOCA Community</h4><figure id="" class="w-richtext-figure-type-image w-richtext-align-fullwidth" style="max-width:1680px" data-rt-type="image" data-rt-align="fullwidth" data-rt-max-width="1680px"><div id=""><img src="https://uploads-ssl.webflow.com/60c7be61132e3ad0b40a333d/632bd7f50da8ef2eb974921b_210608_ha_toca_training_017_LowRes.jpg" alt="Soccer trainers meeting young soccer players" id="" width="auto" height="auto" loading="auto"></div></figure><p id="">From our friendly front desk staff to our best-in-class trainers, TOCA is dedicated to helping you become the player you want to be. </p><h4 id="">Try A FREE Kickoff Session</h4><p id="">Click the links below to learn more about our different training programs below:</p><ul id=""><li id=""><a href="/center-programs/${centerName}-2soccer-02individualtraining">Individual Training</a></li><li id=""><a href="/center-programs/${centerName}-2soccer-03elitetraining">Elite Training</a></li><li id=""><a href="/center-programs/${centerName}-2soccer-04grouptraining">Group Training</a></li><li id=""><a href="/center-programs/${centerName}-2soccer-05teamtraining">Team Training</a></li><li><a href="/center-programs/${centerName}-2soccer-08adultleagues">Adult Leagues</a></li><li><a href="/center-programs/${centerName}-02soccer-09youthleagues">Youth Leagues</a></li></ul><h4 id="">Want To Try a FREE Session?</h4><p id="">Fill out the form on this page and select <strong id="">Free Kickoff</strong> under program. Our center will contact you shortly to book your free kickoff session!<br></p>`,
    slug: `${centerName}-1abouttocafootball`,
    "hero-slider-image-first": {
      fileId: "64492d7ee2522e6c7f2b5677",
      url: "https://uploads-ssl.webflow.com/60c7be61132e3ad0b40a333d/6345ecae987e9dfe8fb4a798_632bd5624529da25276d2d6c_fko.jpeg",
      alt: null,
    },
    states: ["64492d7ee2522e0a132b5516"],
    "phone-number-2": "000-000-0000",
    mytoca: false,
  },
  {
    _archived: false,
    _draft: true,
    deal: false,
    "choose-program-switch": true,
    popular: false,
    name: `${centerName} Soccer`,
    "body-description": "",
    "external-display-name": "Soccer",
    "rich-text": "",
    "sub-programs": [
      "64492d7ee2522ee44b2b556d",
      "64492d7ee2522e00a92b5510",
      "64492d7ee2522e0b1e2b54c8",
      "64492d7ee2522e1f9b2b54b4",
      "64492d7ee2522e45f12b54b1",
      "64492d7ee2522ed8f82b5574",
    ],
    slug: `${centerName}-2soccer`,
    centers: ["64492d7ee2522edf462b5519"],
    states: ["64492d7ee2522e0a132b5516"],
    "phone-number-2": "000-000-0000",
    mytoca: false,
  },
  {
    _archived: false,
    _draft: true,
    deal: false,
    "choose-program-switch": false,
    popular: false,
    name: `${centerName} Soccer Free Kickoff`,
    "external-display-name": "Free Kickoff",
    "rich-text":
      '<h4 id="">Sign Up for a FREE Player Assessment!</h4><figure id="" class="w-richtext-figure-type-video w-richtext-align-fullwidth" style="padding-bottom:56.206088992974244%" data-rt-type="video" data-rt-align="fullwidth" data-rt-max-width="" data-rt-max-height="56.206088992974244%" data-rt-dimensions="854:480" data-page-url="https://youtu.be/rq7YTpFf-yE"><div id=""><iframe allowfullscreen="true" frameborder="0" scrolling="no" src="https://www.youtube.com/embed/rq7YTpFf-yE" title="TOCA Football | Book Your FREE Kickoff"></iframe></div></figure><h4 id="">What You\'ll Experience in a TOCA Kickoff</h4><ul id=""><li id=""><strong id="">Tech-Enhanced Training</strong>: You will experience the next generation of training with our innovative and cutting-edge technology!</li><li id=""><strong id="">Long-Term Goals</strong>: Our trainers will leverage your strengths, pinpoint areas for improvement, and develop a plan of action for your long-term goals.</li><li id=""><strong id="">Best-In-Class Trainers</strong>: Meet our experienced trainers who are lifelong players; many are current or former professional players!</li></ul><h4 id="">How To Sign Up</h4><p id="">Please fill out the form on this page, and our center will contact you soon to book your TOCA Kickoff! </p>',
    slug: `${centerName}-2soccer-01freekickoff`,
    "hero-slider-image-first": {
      fileId: "64492d7ee2522e80bd2b5661",
      url: "https://uploads-ssl.webflow.com/60c7be61132e3ad0b40a333d/632bd256bd8a0dd32cc5cbaa_210608_ha_toca_training_018_LowRes.jpg",
      alt: null,
    },
    centers: [],
    states: ["64492d7ee2522e0a132b5516"],
    "phone-number-2": "000-000-0000",
    mytoca: false,
  },
  {
    _archived: false,
    _draft: true,
    deal: false,
    "choose-program-switch": false,
    popular: false,
    "sort-order": 5,
    name: `${centerName} Soccer Youth Leagues`,
    "body-description": "",
    "external-display-name": "Youth Leagues",
    "rich-text": `<figure id="" class="w-richtext-figure-type-image w-richtext-align-fullwidth" style="max-width:1920px" data-rt-type="image" data-rt-align="fullwidth" data-rt-max-width="1920px"><div id=""><img src="https://uploads-ssl.webflow.com/60c7be61132e3ad0b40a333d/636098b342eb83ca31e439dc_youth-leagues-2.jpg" loading="lazy" id="" width="auto" height="auto"></div></figure><p id="">Drop by TOCA ${centerName} and join one of our Youth Leagues for some fun footy competition! </p><h4 id="">Highlights</h4><ul id=""><li id="">Open to all skill levels</li><li id="">Have fun with friends or make new ones!</li></ul><p id="">‍</p>`,
    slug: `${centerName}-2soccer-09youthleagues`,
    "hero-slider-image-first": {
      fileId: "64492d7ee2522e78032b56e5",
      url: "https://uploads-ssl.webflow.com/60c7be61132e3ad0b40a333d/6360989c1e9ac293763766c2_youth-leagues.jpg",
      alt: null,
    },
    states: ["64492d7ee2522e0a132b5516"],
    "phone-number-2": "000-000-0000",
    mytoca: false,
  },
  {
    _archived: false,
    _draft: true,
    deal: false,
    "choose-program-switch": false,
    popular: false,
    name: `${centerName} Soccer Adult Leagues`,
    "body-description": "",
    "external-display-name": "Adult Leagues",
    "rich-text":
      '<p id="">Looking for a night of footy, friends, and fun? Check out TOCA Leagues!</p><figure id="" class="w-richtext-figure-type-image w-richtext-align-fullwidth" style="max-width:1680px" data-rt-type="image" data-rt-align="fullwidth" data-rt-max-width="1680px"><div id=""><img src="https://uploads-ssl.webflow.com/60c7be61132e3ad0b40a333d/632be2e29a475b4577b89032_210608_ha_toca_league_021_LowRes.jpg" alt="Woman and man playing soccer" id="" width="auto" height="auto" loading="auto"></div></figure><p id="">Meet new friends, enjoy a refreshing beverage, and most importantly, get a taste of the TOCA community! Whether you\'re a former player looking to stay fit or a complete beginner looking to have fun with friends, TOCA has a league for all players.</p><figure id="" class="w-richtext-figure-type-image w-richtext-align-fullwidth" style="max-width:1680px" data-rt-type="image" data-rt-align="fullwidth" data-rt-max-width="1680px"><div id=""><img src="https://uploads-ssl.webflow.com/60c7be61132e3ad0b40a333d/632be3100da8ef81af75383d_210608_ha_toca_league_019_LowRes.jpg" alt="Group handshake after soccer game" id="" width="auto" height="auto" loading="auto"></div></figure><h4 id="">Contact Us</h4><p id="">Please fill out the form on this page, and our center will contact you to discuss Adult Leagues.</p>',
    slug: `${centerName}-2soccer-08adultleagues`,
    "hero-slider-image-first": {
      fileId: "64492d7ee2522e80622b568a",
      url: "https://uploads-ssl.webflow.com/60c7be61132e3ad0b40a333d/6345ecb04877b432e93c01cb_632650b5f8acef2e0a64ea7a_210608_ha_toca_league_031_LowRes.jpeg",
      alt: null,
    },
    states: ["64492d7ee2522e0a132b5516"],
    "phone-number-2": "000-000-0000",
    mytoca: false,
  },
  {
    _archived: false,
    _draft: true,
    deal: false,
    "choose-program-switch": false,
    popular: false,
    name: `${centerName} Soccer Team Training`,
    "body-description": "",
    "external-display-name": "Team Training",
    "rich-text":
      '<p id="">You work hard to develop quality players capable of playing at the elite levels of the beautiful game. Turbocharge your players’ development with TOCA’s exclusive, tech-enabled training techniques that will rapidly improve their technical skills and game awareness.&nbsp;</p><p id="">TOCA can also collaborate with you to build custom programming that augments your methodology and helps players reach their potential. Through game-like experiences featuring consistently repeatable touch-building exercises, TOCA’s innovative soccer tech drives improved technical skill, game awareness, and creativity.&nbsp;</p><p id="">Adding TOCA’s innovative soccer training technology to your player development strategy will give them the cutting edge needed to excel for what comes next. Contact us today to set up a free training session for your club or team.</p><h4 id="">Contact Us</h4><p id="">Please fill out the form on this page, and our center will contact you to discuss Team Training.</p><p id="">‍</p>',
    slug: `${centerName}-2soccer-05teamtraining`,
    "hero-slider-image-first": {
      fileId: "64492d7ee2522e7cca2b5681",
      url: "https://uploads-ssl.webflow.com/60c7be61132e3ad0b40a333d/6345ecafbbe8d957b0ec57f4_632c8a02e4a3bd333d345756_team-training.jpeg",
      alt: null,
    },
    states: ["64492d7ee2522e0a132b5516"],
    "phone-number-2": "000-000-0000",
    mytoca: false,
  },
  {
    _archived: false,
    _draft: true,
    deal: false,
    "choose-program-switch": false,
    popular: false,
    "sort-order": 6,
    name: `${centerName} Soccer Group Training`,
    "body-description": "",
    "external-display-name": "Group Training",
    "rich-text":
      '<p id="">TOCA Group Training provides a group of up to five similarly-skilled players our tech-enhanced soccer experience at a reduced price. It is the perfect solution for players seeking an affordable and challenging training environment.</p><figure id="" class="w-richtext-figure-type-image w-richtext-align-fullwidth" style="max-width:1680px" data-rt-type="image" data-rt-align="fullwidth" data-rt-max-width="1680px"><div id=""><img src="https://uploads-ssl.webflow.com/60c7be61132e3ad0b40a333d/634cf4d03b32697d94fcece9_210608_ha_toca_training_034_LowRes.jpg" loading="lazy" id="" width="auto" height="auto"></div></figure><p id="">Each player in the group receives individualized instruction from TOCA’s professional trainers. Group sessions utilize TOCA’s exclusive soccer tech, including the Touch Trainer and Smart Targets, to help players rapidly develop their touch, technique, and game awareness.</p><h4 id="">Details</h4><ul id=""><li id="">Ages: 7-Adult</li></ul><h4 id="">Highlights</h4><ul id=""><li id="">Affordable and competitive group training</li><li id="">Group 4-5 similar-level athletes</li><li id="">Train with TOCA’s proprietary technology</li></ul><h4 id="">Contact Us</h4><p id="">Fill out the form on this page, and our staff will reach out to you to discuss Group Training.</p><p id="">‍</p>',
    "hero-slider-image-first": {
      fileId: "64492d7ee2522eb0292b56d6",
      url: "https://uploads-ssl.webflow.com/60c7be61132e3ad0b40a333d/634cf4a20007a1c18e3141b0_210608_ha_toca_training_037_LowRes.jpg",
      alt: null,
    },
    slug: `${centerName}-2soccer-04grouptraining`,
    states: ["64492d7ee2522e0a132b5516"],
    "phone-number-2": "000-000-0000",
    mytoca: false,
  },
  {
    _archived: false,
    _draft: true,
    deal: false,
    "choose-program-switch": false,
    popular: false,
    name: `${centerName} Soccer Elite Training`,
    "body-description": "",
    "external-display-name": "Elite Training",
    "rich-text":
      '<p id="">Got your sights set on playing at a collegiate level? Want to play on the same pitch as the pros? As the competition gets tougher, give yourself a winning edge like pros Jane Campbell (Houston Dash goalkeeper) or Gyasi Zardes (Colorado Rapids striker) who stay sharp by training at TOCA.</p><figure id="" class="w-richtext-figure-type-image w-richtext-align-fullwidth" style="max-width:1080px" data-rt-type="image" data-rt-align="fullwidth" data-rt-max-width="1080px"><div id=""><img src="https://uploads-ssl.webflow.com/60c7be61132e3ad0b40a333d/634ce395a42202f20de7d258_Jane-Campbell-118.jpg" loading="lazy" id="" width="auto" height="auto"></div></figure><p id="">TOCA’s elite training takes you through a guided, tech-enhanced soccer experience designed to rapidly improve your skills. The key is TOCA’s proprietary technology, including the Touch Trainer, Smart Targets, Studio Screens, and personalized data tracking, that take your game to the next level.</p><figure id="" class="w-richtext-figure-type-image w-richtext-align-fullwidth" style="max-width:1080px" data-rt-type="image" data-rt-align="fullwidth" data-rt-max-width="1080px"><div id=""><img src="https://uploads-ssl.webflow.com/60c7be61132e3ad0b40a333d/634ce3dde6cf58f6ecded25c_Jane-Campbell-528.jpg" loading="lazy" id="" width="auto" height="auto"></div></figure><p id="">Overall, you get at least 250 match-quality touches on the ball per TOCA training session - equivalent to a week full of practices! Additionally, you can see your progress during each training session through real-time stats that give you data-driven feedback on your accuracy, efficiency, quickness, and more.&nbsp;</p><figure id="" class="w-richtext-figure-type-image w-richtext-align-fullwidth" style="max-width:1080px" data-rt-type="image" data-rt-align="fullwidth" data-rt-max-width="1080px"><div id=""><img src="https://uploads-ssl.webflow.com/60c7be61132e3ad0b40a333d/634ce3c35cb8ac6562049fb5_Jane-Campbell-1439.jpg" loading="lazy" id="" width="auto" height="auto"></div></figure><p id="">From your first touch and ball control to in-game awareness and decision-making, TOCA’s innovative soccer technology and professional trainers will develop and sharpen every aspect of your game. Become the player you want to be with TOCA training.</p><h4 id="">Details</h4><ul id=""><li id="">Ages: 7-Adult</li><li id="">Cost: Starting at $69/session</li></ul><h4 id="">Highlights</h4><ul id=""><li id="">Train with TOCA’s innovative technology</li><li id="">Dedicated 1-on-1 training session</li><li id="">Quickly improve first touch and awareness</li></ul><h4 id="">Contact Us</h4><p id="">Please fill out the form on this page, and our center will contact you to discuss Elite Training.</p><h4 id="">Want To Try a FREE Session First?</h4><p id="">Fill out the form on this page and select <strong id="">Free Kickoff</strong> under program. Our center will contact you shortly to book your free kickoff session!</p><p id="">‍</p>',
    slug: `${centerName}-2soccer-03elitetraining`,
    "hero-slider-image-first": {
      fileId: "64492d7ee2522e374d2b5685",
      url: "https://uploads-ssl.webflow.com/60c7be61132e3ad0b40a333d/6345ecaf623ccabeb2ef04a8_6311e73a08f13d6f8c7f28b9_62f599d07ff2dda59b0ce286_soccer-individual-training.jpeg",
      alt: null,
    },
    states: ["64492d7ee2522e0a132b5516"],
    "phone-number-2": "000-000-0000",
    mytoca: false,
  },
  {
    _archived: false,
    _draft: true,
    deal: false,
    "choose-program-switch": false,
    popular: false,
    "sort-order": 7,
    name: `${centerName} Soccer Individual Training`,
    "body-description": "",
    "external-display-name": "Individual Training",
    "rich-text":
      '<p id="">The next game is coming up, and your team needs you to bring it. TOCA training will help you improve quicker than traditional practice regimens, so you’re ready to crush it with the team.</p><figure id="" class="w-richtext-figure-type-image w-richtext-align-fullwidth" style="max-width:1680px" data-rt-type="image" data-rt-align="fullwidth" data-rt-max-width="1680px"><div id=""><img src="https://uploads-ssl.webflow.com/60c7be61132e3ad0b40a333d/61943405426fec4317579192_210608_ha_toca_training_025_LowRes.jpg" alt="Young girl training with TOCA Smart Targets" id="" width="auto" height="auto" loading="auto"></div></figure><p id="">TOCA’s 1-on-1 training takes you through a guided, tech-enhanced soccer experience designed to rapidly improve your skills. The key is TOCA’s proprietary technology, including the Touch Trainer, Smart Targets, Studio Screens, and personalized data tracking, that take your game to the next level.</p><figure id="" class="w-richtext-figure-type-image w-richtext-align-fullwidth" style="max-width:1680px" data-rt-type="image" data-rt-align="fullwidth" data-rt-max-width="1680px"><div id=""><img src="https://uploads-ssl.webflow.com/60c7be61132e3ad0b40a333d/632bd081d5469fcf0a1625ac_210608_ha_toca_training_026_LowRes.jpg" alt="TOCA Touch Trainer ball machine" id="" width="auto" height="auto" loading="auto"></div></figure><p id="">Overall, you get at least 250 match-quality touches on the ball per TOCA training session - equivalent to a week full of practices! Additionally, you can see your progress during each training session through real-time stats that give you data-driven feedback on your accuracy, efficiency, quickness, and more.</p><p id="">From your first touch and ball control to in-game awareness and decision-making, TOCA’s innovative soccer technology and professional trainers will develop and hone every aspect of your game. Become the player you want to be with TOCA training.</p><figure id="" class="w-richtext-figure-type-image w-richtext-align-fullwidth" style="max-width:1680px" data-rt-type="image" data-rt-align="fullwidth" data-rt-max-width="1680px"><div id=""><img src="https://uploads-ssl.webflow.com/60c7be61132e3ad0b40a333d/632bd256bd8a0dd32cc5cbaa_210608_ha_toca_training_018_LowRes.jpg" alt="Young girl and soccer trainer celebrating" id="" width="auto" height="auto" loading="auto"></div></figure><h4 id="">Details</h4><ul id=""><li id="">Ages: 7-Adult</li><li id="">Cost: Starting at $69/session</li></ul><h4 id="">Highlights</h4><ul id=""><li id="">Train with TOCA’s innovative technology</li><li id="">Dedicated 1-on-1 training session</li><li id="">Quickly improve first touch and awareness</li></ul><h4 id="">Contact Us</h4><p id="">Please fill out the form on this page, and our center will contact you to discuss Individual Training.</p><h4 id="">Want To Try a FREE Session First?</h4><p id="">Fill out the form on this page and select <strong id="">Free Kickoff</strong> under program. Our center will contact you shortly to book your free kickoff session!</p>',
    slug: `${centerName}-2soccer-02individualtraining`,
    "hero-slider-image-first": {
      fileId: "64492d7ee2522e24d72b5688",
      url: "https://uploads-ssl.webflow.com/60c7be61132e3ad0b40a333d/6345ecafa2b199654cb4cfe0_619433d70f903f490c6ab435_210608_ha_toca_training_023_LowRes.jpeg",
      alt: null,
    },
    states: ["64492d7ee2522e0a132b5516"],
    "phone-number-2": "000-000-0000",
    mytoca: false,
  },
];
exports.getCenterPrograms = getCenterPrograms;